### ISSUE TITLE
Unable to parse Postgresql rc version

### ISSUE THREAD

**Issue by petrcech** [ludeeus/awesomeversion#246]
### The problem

Hi,
it seems awesomeversion is unable to parse "16rc1" as a version string. With default settings it returns no error, but the "major" version is empty although the release_candidate is true. Simple strategy throws an exception.

Thanks

### Operating system

Debian

### Python version

3.11

### Problem-relevant code

```python
import awesomeversion
awesomeversion.AwesomeVersion("16rc1",ensure_strategy=awesomeversion.AwesomeVersionStrategy.SIMPLEVER, find_first_match=True)
```

### Traceback/Error logs

```txt
>>> a=awesomeversion.AwesomeVersion("16rc1",ensure_strategy=awesomeversion.AwesomeVersionStrategy.SIMPLEVER, find_first_match=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cech/build/PYTHON/t/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 136, in __init__
    raise AwesomeVersionStrategyException(
awesomeversion.exceptions.AwesomeVersionStrategyException: Strategy PEP 440 does not match ['SimpleVer'] for 16rc1
```

**Comment by ludeeus** [comment]
This is not a valid simple version, that can only be numbers.
